### ISSUE TITLE
Using pack_data.py with Persona 5 Scramble results in crashing on boot

### ISSUE THREAD

**Issue by QTKO** [3096/three-houses-scripts#1]
I've been trying to translate some of the msgData from Persona 5 Scramble and using the LINKDATA repacker crashes the game on boot. I've tried only changing one numbered bin at a time, but none work correctly. The only difference is that only changing 0.bin freezes the console when loading the game from the Home menu (where the Switch logo pops up), while the others show the Atmosphere crash screen rather than freezing.

These are the edited and repacked LINKDATA files that crash.

https://drive.google.com/open?id=1spvI8IBA8VC-aLIREqK6WV7lae9ayKji
https://drive.google.com/open?id=1TLvB-htTw0CFgQdWlwIOwOESOXEj3Fju
https://drive.google.com/open?id=1qChAqpm7r_JhN6HmJymfbmBhO-6l4Mxm
https://drive.google.com/open?id=18ku3z483vQ-LVOz1ki8LA8ZZ4M6mcHj4

Here's the segments within LINKDATA.BIN that I edited.
https://drive.google.com/file/d/17SRtP90ye6IAvgpweeQsbnZYrAiMMeRQ

And here's the original LINKDATA.BIN for reference.
https://drive.google.com/file/d/1ONpH64vp9j64CNG8VZYNHJmhHU4UG90j

**Comment by 3096** [comment]
I think I found the issue. I had 2 versions of that script and one didn't allow size changes and I later forgot about the limitation and just pushed that version. 

Anyways, I've pushed a fixed version. Try if it works now and let me know
https://github.com/3096/koeipy/blob/master/pack_data.py

**Comment by QTKO** [comment]
It works! Thank you so much!

![2020050319511100-4EAFD1BE1FD8243F99E01D6EF6C04B23](https://user-images.githubusercontent.com/41129743/80928735-4953f200-8d5b-11ea-907e-48ad4aada18f.jpg)
![2020050320352400-4EAFD1BE1FD8243F99E01D6EF6C04B23](https://user-images.githubusercontent.com/41129743/80928914-cb90e600-8d5c-11ea-987a-57c8e915ddc9.jpg)
https://streamable.com/clavs1
